"""Responsive three-column HUD layout; all actions delegate to Desktop.submit."""
import tkinter as tk
from ui.theme import BG, PANEL, EDGE, CYAN, GLOW, TEXT, MUTED, label, button, panel, text_box
from ui.widgets.ai_core import AICore, Waveform
from ui.widgets.telemetry import Gauge, PerformanceGraph

def build(d):
    root = d.root
    root.columnconfigure(0, weight=1)
    root.rowconfigure(1, weight=1)
    header = tk.Frame(root, bg=BG)
    header.grid(row=0, column=0, sticky='ew', padx=18, pady=(10, 8))
    label(header, 'J A R V I S', 24, CYAN).pack(side='left')
    label(header, 'PERSONAL AI SYSTEM\nCOMMAND CENTER / V2.0', 8, MUTED, justify='left').pack(side='left', padx=16)
    d.header_status = label(header, '● SYSTEM ONLINE\nLOCAL MODE', 9, CYAN, justify='left')
    d.header_status.pack(side='left', padx=8)
    for caption, action in [('×', d.request_close), ('□', d.maximize), ('—', d.hide), ('SETTINGS', d.settings), ('COMMANDS', lambda: d.palette(True))]:
        button(header, caption, action).pack(side='right', padx=3)
    d.clock_label = label(header, '', 10, TEXT, justify='right')
    d.clock_label.pack(side='right', padx=14)
    dashboard = tk.Frame(root, bg=BG)
    dashboard.grid(row=1, column=0, sticky='nsew', padx=18)
    dashboard.columnconfigure(0, weight=2, minsize=235)
    dashboard.columnconfigure(1, weight=5, minsize=330)
    dashboard.columnconfigure(2, weight=2, minsize=270)
    dashboard.rowconfigure(0, weight=1)
    d.dashboard = dashboard
    frame, left = panel(dashboard, 'SYSTEM TELEMETRY', '01')
    d.left_panel = frame
    frame.grid(row=0, column=0, sticky='nsew', padx=(0, 10))
    gauges = tk.Frame(left, bg=PANEL)
    gauges.pack(fill='x')
    gauges.columnconfigure((0, 1), weight=1)
    d.gauges = {}
    for i, key in enumerate(('cpu', 'ram', 'battery', 'storage')):
        gauge = Gauge(gauges, key.upper())
        gauge.grid(row=i//2, column=i%2, sticky='ew', pady=1)
        d.gauges[key] = gauge
    d.hardware_label = label(left, 'GPU N/A • BATTERY N/A\nPROCESSES N/A • UPTIME N/A', 8, MUTED, justify='left', anchor='w')
    d.hardware_label.pack(fill='x', pady=(2, 4))
    d.device_label = label(left, 'DEVICE / CONNECTING…', 8, TEXT, anchor='w')
    d.device_label.pack(fill='x')
    tk.Frame(left, bg=EDGE, height=1).pack(fill='x', pady=5)
    d.network_label = label(left, 'INTERNET N/A • WI-FI N/A\n↓ N/A   ↑ N/A', 8, CYAN, justify='left', anchor='w')
    d.network_label.pack(fill='x')
    modes = tk.Frame(left, bg=PANEL)
    modes.pack(fill='x', pady=(4, 2))
    d.graph = PerformanceGraph(left)
    for mode in ('CPU', 'RAM', 'Network'):
        button(modes, mode.upper(), lambda m=mode: d.graph.set_mode(m)).pack(side='left', expand=True, fill='x', padx=1)
    d.graph.pack(fill='both', expand=True)
    frame, center = panel(dashboard, 'ASSISTANT CORE', 'LOCAL / SECURE', glow=True)
    d.core_panel = frame
    frame.grid(row=0, column=1, sticky='nsew', padx=(0, 10))
    d.core = AICore(center)
    d.core.pack(fill='both', expand=True)
    core_status = tk.Frame(center, bg=PANEL)
    core_status.pack(fill='x', pady=3)
    label(core_status, 'J A R V I S', 12, TEXT).pack(side='left', expand=True, anchor='e', padx=(0, 8))
    d.state_label = tk.Label(core_status, text='IDLE', fg=CYAN, bg=PANEL, font=('Consolas', 11, 'bold'))
    d.state_label.pack(side='left', expand=True, anchor='w', padx=(8, 0))
    d.waveform = Waveform(center)
    d.waveform.pack(fill='x')
    mic_row = tk.Frame(center, bg=PANEL)
    mic_row.pack(pady=(3, 2))
    tk.Label(mic_row, textvariable=d.mic_label, fg=MUTED, bg=PANEL, font=('Consolas', 8)).pack(side='left', padx=(0, 12))
    d.mic_button = button(mic_row, '◉ ENABLE MICROPHONE', d.toggle_mic, True)
    d.mic_button.pack(side='left')
    label(center, 'VOICE / LOCAL RECOGNITION / NO AUDIO UPLOAD', 7, MUTED).pack(pady=(3, 0))
    frame, right = panel(dashboard, 'MISSION CONTROL', '03')
    d.right_panel = frame
    frame.grid(row=0, column=2, sticky='nsew')
    quick = tk.Frame(right, bg=PANEL)
    quick.pack(fill='x')
    quick.columnconfigure((0, 1, 2), weight=1)
    for i, app in enumerate(d.config['dashboard']['quick_launch']):
        caption = {'File Explorer': 'EXPLORER', 'Settings': 'WINDOWS'}.get(app, app.upper())
        button(quick, caption, lambda name=app: d.submit('open '+name)).grid(row=i//3, column=i%3, sticky='ew', padx=2, pady=2)
    tk.Frame(right, bg=EDGE, height=1).pack(fill='x', pady=8)
    d.weather_label = label(right, 'WEATHER / OPTIONAL\nConfigure location in Settings', 9, MUTED, justify='left', anchor='w')
    d.weather_label.pack(fill='x')
    tk.Frame(right, bg=EDGE, height=1).pack(fill='x', pady=8)
    row = tk.Frame(right, bg=PANEL)
    row.pack(fill='x')
    label(row, 'UPCOMING', 9, CYAN).pack(side='left')
    button(row, 'VIEW ALL', d.reminders_window).pack(side='right')
    d.reminder_label = label(right, 'No pending reminders.', 9, MUTED, justify='left', anchor='nw')
    d.reminder_label.pack(fill='both', expand=True, pady=(4, 2))
    notes = tk.Frame(right, bg=PANEL)
    notes.pack(fill='x', pady=(3, 4))
    button(notes, '+ NEW NOTE', d.new_note).pack(side='left', expand=True, fill='x', padx=(0, 3))
    button(notes, 'VIEW NOTES', d.notes).pack(side='left', expand=True, fill='x', padx=(3, 0))
    tk.Frame(right, bg=EDGE, height=1).pack(fill='x', pady=5)
    d.media_label = label(right, 'MEDIA / No active session', 8, MUTED, anchor='w')
    d.media_label.pack(fill='x', pady=(0, 4))
    media = tk.Frame(right, bg=PANEL)
    media.pack(fill='x')
    for caption, command in [('⏮', 'previous song'), ('▶ / Ⅱ', 'toggle music'), ('⏭', 'next song'), ('−', 'decrease volume'), ('MUTE', 'mute'), ('+', 'increase volume')]:
        button(media, caption, lambda c=command: d.submit(c)).pack(side='left', fill='x', expand=True, padx=1)
    lower = tk.Frame(root, bg=BG)
    lower.grid(row=2, column=0, sticky='ew', padx=18, pady=(9, 7))
    lower.columnconfigure(0, weight=5)
    lower.columnconfigure(1, weight=2)
    lower.columnconfigure(2, weight=2)
    frame, body = panel(lower, 'LIVE TRANSCRIPT', 'MEMORY ONLY')
    frame.grid(row=0, column=0, sticky='nsew', padx=(0, 10))
    d.output = text_box(body, height=3, width=40)
    d.output.pack(fill='both', expand=True)
    d.output.configure(state='disabled')
    d.output.tag_configure('speaker', foreground=CYAN, font=('Consolas', 10, 'bold'))
    d.output.tag_configure('you', foreground=MUTED, font=('Consolas', 9))
    frame, body = panel(lower, 'RECENT ACTIVITY', 'LOCAL')
    frame.grid(row=0, column=1, sticky='nsew', padx=(0, 10))
    d.history = text_box(body, height=3, width=24)
    d.history.pack(fill='both', expand=True)
    d.history.configure(state='disabled')
    frame, body = panel(lower, 'NOTIFICATIONS', '●')
    frame.grid(row=0, column=2, sticky='nsew')
    d.notification_label = label(body, '', 8, MUTED, justify='left', anchor='nw', wraplength=230)
    d.notification_label.pack(fill='both', expand=True)
    terminal = tk.Frame(root, bg='#060e1a', highlightbackground=EDGE, highlightthickness=1)
    terminal.grid(row=3, column=0, sticky='ew', padx=18)
    label(terminal, ' > ', 18, CYAN).pack(side='left', padx=(8, 0))
    d.entry = tk.Entry(terminal, bg='#060e1a', fg=TEXT, insertbackground=CYAN, relief='flat', font=('Consolas', 12))
    d.entry.pack(side='left', fill='x', expand=True, ipady=11, padx=8)
    d.entry.bind('<Return>', lambda _: d.submit())
    d.entry.bind('<FocusIn>', lambda _: terminal.configure(highlightbackground=GLOW))
    d.entry.bind('<FocusOut>', lambda _: terminal.configure(highlightbackground=EDGE))
    button(terminal, 'CLEAR HISTORY', d.clear_history).pack(side='right', padx=7)
    button(terminal, 'SEND ↵', d.submit, True).pack(side='right', padx=5)
    footer = tk.Frame(root, bg=BG)
    footer.grid(row=4, column=0, sticky='ew', padx=18, pady=(5, 6))
    label(footer, '● LOCAL FIRST', 8, CYAN).pack(side='left')
    label(footer, 'CTRL+SPACE  INPUT    CTRL+K  PALETTE    F11  FULLSCREEN', 8, MUTED).pack(side='left', padx=18)
    button(footer, 'SCREENSHOTS ↗', lambda: d.submit('open screenshots')).pack(side='right')
    d.entry.focus_set()
